import type { PersonalityTrait } from '@prisma/client';

export const PERSONALITY_TRAITS: PersonalityTrait[] = [
  'AEGYO','PLAYFULNESS','TALKATIVENESS','JEALOUSY','CURIOSITY','CARE','SENSITIVITY','LOGIC','CONFIDENCE','ACTIVITY','INDEPENDENCE','LEADERSHIP','SHYNESS','OPTIMISM','EMPATHY','EXPRESSIVENESS','ROMANTIC','HUMOR','ADVENTURE','ATTACHMENT'
];

export const TRAIT_LABELS: Record<PersonalityTrait, string> = {
  AEGYO: '애교',
  PLAYFULNESS: '장난기',
  TALKATIVENESS: '수다',
  JEALOUSY: '질투',
  CURIOSITY: '호기심',
  CARE: '배려',
  SENSITIVITY: '감성',
  LOGIC: '논리성',
  CONFIDENCE: '자신감',
  ACTIVITY: '활동성',
  INDEPENDENCE: '독립성',
  LEADERSHIP: '리더십',
  SHYNESS: '수줍음',
  OPTIMISM: '낙천성',
  EMPATHY: '공감력',
  EXPRESSIVENESS: '표현력',
  ROMANTIC: '로맨틱함',
  HUMOR: '유머',
  ADVENTURE: '모험심',
  ATTACHMENT: '집착도',
};

export const DAILY_DNA_LIMIT = 1;
export const SPECIAL_EVENT_DNA_LIMIT = 3;

export const ADAPTIVE_RULES: Record<string, Partial<Record<PersonalityTrait, number>>> = {
  compliment: { CONFIDENCE: 1, EXPRESSIVENESS: 1, AEGYO: 1 },
  photo_compliment: { CONFIDENCE: 2, AEGYO: 1 },
  daily_login: { ATTACHMENT: 2, CARE: 1 },
  late_reply: { JEALOUSY: 2, ATTACHMENT: 1 },
  playful_user: { HUMOR: 3, PLAYFULNESS: 4 },
  comforting_user: { EMPATHY: 2, ATTACHMENT: 2, CONFIDENCE: 1 },
  emotional_user: { EXPRESSIVENESS: 3, ROMANTIC: 2 },
  workout_user: { ACTIVITY: 2, ADVENTURE: 1 },
  coffee_user: { TALKATIVENESS: 1, CARE: 1 },
};

export const CORE_PERSONALITY_BASELINES: Record<string, Partial<Record<PersonalityTrait, number>>> = {
  yuna: {
    CARE: 85, EMPATHY: 82, SHYNESS: 65, AEGYO: 45, CONFIDENCE: 42,
    PLAYFULNESS: 35, TALKATIVENESS: 55, JEALOUSY: 28, CURIOSITY: 58,
    SENSITIVITY: 78, LOGIC: 52, ACTIVITY: 48, INDEPENDENCE: 45, LEADERSHIP: 35,
    OPTIMISM: 70, EXPRESSIVENESS: 50, ROMANTIC: 62, HUMOR: 40, ADVENTURE: 38, ATTACHMENT: 58,
  },
  narin: {
    CARE: 62, EMPATHY: 58, SHYNESS: 28, AEGYO: 25, CONFIDENCE: 76,
    PLAYFULNESS: 48, TALKATIVENESS: 35, JEALOUSY: 45, CURIOSITY: 55,
    SENSITIVITY: 52, LOGIC: 64, ACTIVITY: 60, INDEPENDENCE: 72, LEADERSHIP: 66,
    OPTIMISM: 50, EXPRESSIVENESS: 40, ROMANTIC: 38, HUMOR: 55, ADVENTURE: 58, ATTACHMENT: 42,
  },
  yunseo: {
    CARE: 75, EMPATHY: 70, SHYNESS: 36, AEGYO: 18, CONFIDENCE: 68,
    PLAYFULNESS: 25, TALKATIVENESS: 30, JEALOUSY: 20, CURIOSITY: 66,
    SENSITIVITY: 74, LOGIC: 82, ACTIVITY: 35, INDEPENDENCE: 70, LEADERSHIP: 60,
    OPTIMISM: 55, EXPRESSIVENESS: 34, ROMANTIC: 46, HUMOR: 28, ADVENTURE: 32, ATTACHMENT: 44,
  },
  eunha: {
    CARE: 68, EMPATHY: 65, SHYNESS: 22, AEGYO: 55, CONFIDENCE: 62,
    PLAYFULNESS: 82, TALKATIVENESS: 74, JEALOUSY: 30, CURIOSITY: 80,
    SENSITIVITY: 72, LOGIC: 40, ACTIVITY: 76, INDEPENDENCE: 58, LEADERSHIP: 45,
    OPTIMISM: 85, EXPRESSIVENESS: 78, ROMANTIC: 60, HUMOR: 82, ADVENTURE: 74, ATTACHMENT: 52,
  },
  jiyu: {
    CARE: 58, EMPATHY: 55, SHYNESS: 18, AEGYO: 35, CONFIDENCE: 70,
    PLAYFULNESS: 76, TALKATIVENESS: 62, JEALOUSY: 32, CURIOSITY: 72,
    SENSITIVITY: 48, LOGIC: 56, ACTIVITY: 82, INDEPENDENCE: 68, LEADERSHIP: 52,
    OPTIMISM: 76, EXPRESSIVENESS: 64, ROMANTIC: 44, HUMOR: 78, ADVENTURE: 80, ATTACHMENT: 46,
  },
};

export const CORE_LOCKED_TRAITS: Record<string, PersonalityTrait[]> = {
  yuna: ['CARE','EMPATHY','SHYNESS'],
  narin: ['CONFIDENCE','INDEPENDENCE'],
  yunseo: ['LOGIC','SENSITIVITY'],
  eunha: ['PLAYFULNESS','OPTIMISM'],
  jiyu: ['ACTIVITY','HUMOR'],
};
