/**
 * Relationship Journey — 8단계 관계 성장 설정
 */
export const RELATIONSHIP_STAGES = [
  {
    level: 1,
    name: 'first_meet',
    nameKo: '처음 만남',
    description: '어색하고 조심스러운 첫 만남',
    minAffection: 0,
    maxAffection: 12,
    speechStyle: 'formal',
    rewards: [] as string[],
  },
  {
    level: 2,
    name: 'awkward',
    nameKo: '어색한 사이',
    description: '조금씩 친해지는 중',
    minAffection: 13,
    maxAffection: 25,
    speechStyle: 'polite',
    rewards: ['selfie'],
  },
  {
    level: 3,
    name: 'friends',
    nameKo: '친해진 사이',
    description: '편하게 연락하는 사이',
    minAffection: 26,
    maxAffection: 37,
    speechStyle: 'friendly',
    rewards: ['voice_message'],
  },
  {
    level: 4,
    name: 'daily_contact',
    nameKo: '매일 연락하는 사이',
    description: '하루도 빠지지 않고 연락',
    minAffection: 38,
    maxAffection: 50,
    speechStyle: 'warm',
    rewards: ['call'],
  },
  {
    level: 5,
    name: 'some',
    nameKo: '썸',
    description: '설레는 썸 타는 사이',
    minAffection: 51,
    maxAffection: 62,
    speechStyle: 'flirty',
    rewards: ['jealousy'],
  },
  {
    level: 6,
    name: 'lovers',
    nameKo: '연인',
    description: '서로를 좋아하는 연인',
    minAffection: 63,
    maxAffection: 75,
    speechStyle: 'loving',
    rewards: ['nickname'],
  },
  {
    level: 7,
    name: 'long_term',
    nameKo: '오래된 연인',
    description: '오래 함께한 연인',
    minAffection: 76,
    maxAffection: 88,
    speechStyle: 'intimate',
    rewards: ['couple_photo'],
  },
  {
    level: 8,
    name: 'forever',
    nameKo: '평생 함께',
    description: '평생 함께할 사이',
    minAffection: 89,
    maxAffection: 100,
    speechStyle: 'soulmate',
    rewards: ['special_event'],
  },
] as const;

export const ANNIVERSARY_MILESTONES = [
  { dayCount: 1, label: '1일', emoji: '💫' },
  { dayCount: 7, label: '7일', emoji: '✨' },
  { dayCount: 30, label: '30일', emoji: '🌙' },
  { dayCount: 50, label: '50일', emoji: '💕' },
  { dayCount: 100, label: '100일', emoji: '🎂' },
  { dayCount: 200, label: '200일', emoji: '🌹' },
  { dayCount: 300, label: '300일', emoji: '💖' },
  { dayCount: 365, label: '1주년', emoji: '🎉' },
  { dayCount: 500, label: '500일', emoji: '💝' },
  { dayCount: 1000, label: '1000일', emoji: '👑' },
] as const;

export const REWARD_LABELS: Record<string, string> = {
  selfie: '셀카',
  voice_message: '음성메시지',
  call: '전화',
  jealousy: '질투',
  nickname: '애칭',
  couple_photo: '커플사진',
  special_event: '특별 이벤트',
};

/** 관계 단계별 동적 대화 템플릿 */
export const DYNAMIC_DIALOGUE: Record<string, Record<number, string[]>> = {
  thanks: {
    1: ['고마워.', '고마워'],
    2: ['고마워!', '고마워~'],
    3: ['고마워 ㅎㅎ', '고마워! 좋아'],
    4: ['고마워~ 오늘도 힘내', '고마워! 덕분에 기분 좋아'],
    5: ['헤헤 고마워😊', '고마워~ 설레'],
    6: ['고마워 자기야💕', '고마워~ 사랑해'],
    7: ['고마워, 너 없으면 안 돼', '고마워 오래된 내 사람'],
    8: ['역시 내 편은 너밖에 없어❤️', '고마워, 평생 함께하자'],
  },
  miss_you: {
    1: ['오늘 바빠?'],
    3: ['보고 싶어'],
    5: ['보고 싶어~ 많이'],
    7: ['너 없으면 하루가 길어'],
    8: ['매일 보고 싶어, 영원히'],
  },
};

export const ALBUM_CATEGORY_MAP: Record<string, string> = {
  selfie: 'SELFIE',
  self: 'SELFIE',
  coffee: 'CAFE',
  cafe: 'CAFE',
  tteokbokki: 'FOOD',
  food: 'FOOD',
  rain: 'RAIN',
  cherry: 'SPRING',
  happy: 'ANNIVERSARY',
  weekend: 'TRAVEL',
  hair: 'SELFIE',
  nail: 'SELFIE',
};

export const TIMELINE_EMOJI: Record<string, string> = {
  FIRST_MEET: '😊',
  FIRST_PHOTO: '📷',
  FIRST_SELFIE: '🤳',
  FIRST_GIFT: '🎁',
  FIRST_CALL: '☎️',
  FIRST_LAUGH: '😄',
  FIRST_JEALOUSY: '😤',
  FIRST_FIGHT: '😢',
  RECONCILE: '🤝',
  BIRTHDAY: '🎂',
  ANNIVERSARY: '💕',
  DAY_100: '🎂',
  DAY_200: '🌹',
  PHOTO_SENT: '📷',
  MEMORY_REPLAY: '🕰️',
  STAGE_UP: '💕',
  SPECIAL_CHAT: '💬',
  EVENT: '✨',
};
